export const meshTerms = [
    "Animals",
    "Anti-Bacterial Agents",
    "Cell Line",
    "Disease Models, Animal",
    "Drug Therapy, Combination",
    "Female",
    "Gene Expression Regulation",
    "Genetic Predisposition to Disease",
    "Genome-Wide Association Study",
    "Humans",
    "Male",
    "Mice",
    "Middle Aged",
    "Molecular Sequence Data",
    "Mutation",
    "Neoplasms",
    "Progeria",
    "Rats",
    "Risk Factors",
    "Treatment Outcome",
    "Young Adult",
    "Alzheimer Disease",
    "Anxiety Disorders",
    "Arthritis, Rheumatoid",
    "Asthma",
    "Atherosclerosis",
    "Autism Spectrum Disorder",
    "Bipolar Disorder",
    "Breast Neoplasms",
    "Bronchitis, Chronic",
    "Carcinoma, Hepatocellular",
    "Celiac Disease",
    "Cerebrovascular Disorders",
    "Chlamydia Infections",
    "Chronic Kidney Disease",
    "Chronic Obstructive Pulmonary Disease",
    "Colonic Neoplasms",
    "Colorectal Neoplasms",
    "Coronary Artery Disease",
    "Crohn Disease",
    "Cystic Fibrosis",
    "Dementia",
    "Depressive Disorder, Major",
    "Diabetes Mellitus, Type 1",
    "Diabetes Mellitus, Type 2",
    "Diabetic Retinopathy",
    "Diarrhea",
    "Eating Disorders",
    "Eczema",
    "Endometriosis",
    "Epilepsy",
    "Erectile Dysfunction",
    "Fibromyalgia",
    "Gastritis",
    "Gastroesophageal Reflux",
    "Glaucoma",
    "Gout",
    "Heart Failure",
    "Hemophilia A",
    "Hepatitis B",
    "Hepatitis C",
    "Human Immunodeficiency Virus (HIV)",
    "Hypertension",
    "Hyperthyroidism",
    "Hypothyroidism",
    "Inflammatory Bowel Diseases",
    "Influenza, Human",
    "Insomnia",
    "Irritable Bowel Syndrome",
    "Kidney Neoplasms",
    "Leukemia",
    "Liver Cirrhosis",
    "Lung Neoplasms",
    "Lupus Erythematosus, Systemic",
    "Lymphoma, Non-Hodgkin",
    "Malaria",
    "Melanoma",
    "Migraine Disorders",
    "Multiple Myeloma",
    "Multiple Sclerosis",
    "Myocardial Infarction",
    "Obesity",
    "Osteoarthritis",
    "Osteoporosis",
    "Ovarian Neoplasms",
    "Pancreatic Neoplasms",
    "Parkinson Disease",
    "Peptic Ulcer",
    "Pneumonia",
    "Polycystic Ovary Syndrome",
    "Post-Traumatic Stress Disorder",
    "Prostate Neoplasms",
    "Psoriasis",
    "Pulmonary Embolism",
    "Renal Insufficiency, Chronic",
    "Respiratory Syncytial Virus Infections",
    "Restless Legs Syndrome",
    "Rheumatic Fever",
    "Rheumatoid Arthritis",
    "Schizophrenia",
    "Scleroderma, Systemic",
    "Scoliosis",
    "Seizures",
    "Sickle Cell Anemia",
    "Sleep Apnea, Obstructive",
    "Spinal Stenosis",
    "Stroke",
    "Substance-Related Disorders",
    "Systemic Lupus Erythematosus",
    "Thrombosis",
    "Thyroid Diseases",
    "Tuberculosis",
    "Type 1 Diabetes Mellitus",
    "Type 2 Diabetes Mellitus",
    "Ulcerative Colitis",
    "Urinary Incontinence",
    "Urinary Tract Infections",
    "Uterine Fibroids",
    "Varicose Veins",
    "Venous Thromboembolism"
  ];
  
   
  